name=OTAxpress
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=Minimal OTA update library for ESP32 with user-defined configuration
paragraph=OTAxpress provides secure OTA updates requiring user-defined hostname and password, with WiFi reconnect and LED status indication.
category=Communication
url=https://github.com/Rafeul1997/OTAxpress
architectures=esp32
