name=OTAxpress
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=Fast and minimal OTA update library for ESP32
paragraph=OTAxpress enables quick and easy OTA updates with minimal code, automatic hostname generation, and optional LED status indication.
category=Communication
architectures=esp32
