name=OTAxpress
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=Fast and minimal OTA update library for ESP32
paragraph=OTAxpress provides simple OTA updates with automatic hostname generation, WiFi reconnect, and LED status indication.
category=Communication
architectures=esp32
